# Generated by Django 6.0.6 on 2026-07-03 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Category display name, e.g. 'Tropical Fruits'", max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-safe identifier auto-generated from name.', max_length=110, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the fruit, e.g. 'Red Apple'", max_length=150)),
                ('slug', models.SlugField(blank=True, help_text='URL-safe identifier auto-generated from name.', max_length=160, unique=True)),
                ('description', models.TextField(blank=True, help_text='Short description shown on the product page.')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per unit in INR (₹).', max_digits=6)),
                ('stock', models.PositiveIntegerField(default=0, help_text='Number of units currently in stock.')),
                ('image', models.ImageField(blank=True, help_text='Product image (optional). Upload via admin.', null=True, upload_to='fruits/')),
                ('is_available', models.BooleanField(default=True, help_text='Uncheck to hide this fruit from the store.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='The category this fruit belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fruits', to='store.category')),
            ],
            options={
                'verbose_name': 'Fruit',
                'verbose_name_plural': 'Fruits',
                'ordering': ['name'],
            },
        ),
    ]
