# Generated by Django 6.0.6 on 2026-07-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='unit',
            field=models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('piece', 'piece'), ('box', 'box'), ('basket', 'basket')], default='piece', help_text="The selling unit for this fruit. Use 'g' or 'kg' with the Weight field; 'piece', 'box', or 'basket' for count-based items.", max_length=10),
        ),
        migrations.AddField(
            model_name='fruit',
            name='weight',
            field=models.PositiveIntegerField(blank=True, help_text="Numeric weight/quantity. Only used when Unit is 'g' or 'kg'. E.g. enter 250 for '250 g', or 1 for '1 kg'. Leave blank for piece/box/basket units.", null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit_display',
            field=models.CharField(blank=True, default='', help_text="Unit label at the time of purchase, e.g. '250 g' or 'piece'.", max_length=20),
        ),
    ]
