# Generated by Django 6.0.6 on 2026-07-14 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_unit_weight_to_fruit_and_unit_display_to_orderitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fruit', models.ForeignKey(help_text='The fruit that is wishlisted.', on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='store.fruit')),
                ('user', models.ForeignKey(help_text='The customer who wishlisted this fruit.', on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wishlist Item',
                'verbose_name_plural': 'Wishlist Items',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'fruit')},
            },
        ),
    ]
